SystemOrganization addCategory: #RecognisingStructuralPatterns!
SystemOrganization addCategory: 'RecognisingStructuralPatterns-Experiments'!
SystemOrganization addCategory: 'RecognisingStructuralPatterns-Java'!
SystemOrganization addCategory: 'RecognisingStructuralPatterns-MarkupLanguages'!
SystemOrganization addCategory: 'RecognisingStructuralPatterns-PropertiesParser'!
SystemOrganization addCategory: 'RecognisingStructuralPatterns-StructureParsers'!
SystemOrganization addCategory: 'RecognisingStructuralPatterns-XMLParser'!
